config/routes.rb
Rails.application.routes.draw do
	get "/", to:"posts#index"
	get "/login", to:"sessions#new"
	post "/login", to:"sessions#create"
	get "/logout", to:"sessions#destroy"


	resources :users, :posts, :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end
# create relationships between users/posts and a comment

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
# allows sessions
  private 

  def current_user
  	return unless session[:user_id]
  	@current_user ||= User.find(session[:user_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def new
  @comment = Comment.new
end

def create
	@post = Post.find_by_id(:post_id)
	# create comments and save to specific post
 	@comment = Comment.new(comment_params)
  if @comment.save
    redirect_to posts_path(@post)
  else
    redirect_to "/"
  end
end

def show
  @comment = Comment.find_by_id(params[:id])
end

private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index	
		@posts = Post.all.last(10).sort_by { |r| r.id }.reverse
		@post = Post.find_by_id(params[:id])
	end

  def show
  	@post = Post.find_by_id(params[:id])
  	@user = @post.user
  	@comments = @post.comments
  end

  def new
  end

  def create
 	user = User.find_by_id(session[:user_id])
  post = user.posts.new(post_params)
	  if post.save && user.save
	    redirect_to post_path(post)
	  else
	    redirect_to post_path(new)
	  end
  end

  def edit
  	@post = Post.find_by_id(params[:id])
  end

  def update
  	@post = Post.find_by_id(params[:id])
  	@post.update(post_params)
  	redirect_to post_path(@post)
  end

  def destroy
  end

  private

  def post_params
  	params.require(:post).permit(:id, :title, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
# login functionality
	def create
		user = User.find_by(username: params[:session][:username])
	  if user && user.password == params[:session][:password]
	    session[:user_id] = user.id
	    redirect_to user_path(user)
	  else
	    redirect_to "/login"
	  end
	end

	def destroy
		session[:user_id] = nil
		redirect_to "/login"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = User.all
	end

  def show
  	@user = User.find_by_id(params[:id])
  end

  def new
  	@user = User.new
  end
  # create user
  def create
  	user = User.find_or_create_by(user_params)
  	session[:user_id] = user.id
  	redirect_to user_path(user)
  end

  def edit
  	@user = User.find_by_id(params[:id])
  end

  def update
  	@user = User.find_by_id(params[:id])
  	@user.update(user_params)
  	redirect_to user_path(@user)
  end

  private

  def user_params
  	params.require(:user).permit(:id, :username, :password, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<div class="comments-edit">
	<% if current_user %>
		<%= bootstrap_form_for @comment do |f| %>
			<%= f.hidden_field :post_id, value: params[:post_id] %>
			<%= f.hidden_field :user_id, value: current_user.id %>
		<br>
			<%= f.text_field :content %>
		<br>
			<%= f.submit %>
		<% end %>
	<% end %>
</div>

app/views/comments/new.html.erb
<div class="comments-new">
	<% if current_user %>
		<%= bootstrap_form_for @comment do |f| %>
			<%= f.hidden_field :post_id, value: params[:post_id] %>
			<%= f.hidden_field :user_id, value: current_user.id %>
		<br>
			<%= f.text_field :content %>
		<br>
			<%= f.submit %>
		<% end %>
	<% end %>
</div>

<!-- add comment to post you came from -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
	
  <body>
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">Blog</a>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	      	<li><a href="/">Home</a></li>
	        <% if current_user %>
				    <li><a href="/users/<%= current_user.id %>">My Profile</a></li>
				    <li><a href="/posts/new">Add New Post</a></li>
				    <li><a href="/logout">Logout</a></li>
				  <% else %>
				    <li><a href="/login">Login</a></li>
				    <li><a href="/users/new">Signup</a></li>
				  <% end %>
	      </ul>
	    </div>
	  </div>
	</nav>
 <!-- bootstrap nav bar -->
  <div class="middle">
  	<br>
  	<br>
    <p>You are logged in as: <%= current_user ? current_user.username : "No user signed in." %></p>
    <%= yield %>
   </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="posts-edit">
	<% if current_user %>
		<%= bootstrap_form_for @post do |f| %>
			<%= f.text_field :title %>
		<br>
			<%= f.text_area :content %>
		<br>
			<%= f.submit %>
		<% end %>
	<% end %>
</div>

<!-- edit post -->

app/views/posts/index.html.erb
<div class="home">
	<% if current_user %>
		<% @posts.each do |post| %>
				<div class="front-page-posts">
					<h3> <%= post.title %> </h3>
					<a href="/users/<%= post.user.id %>"> <%= post.user.username %> </a>
					<hr>
					<p><%= post.content %></p>
					<br>
					<a href="/posts/<%= post.id %>"> View </a>
				</div>
		<% end %>
	<% else %>
			<h2 class="warning">You must login/signup</h2>
			<a href="/login"><button class="btn btn-default">Login</button></a>
			<a href="/users/new"><button class="btn btn-default">Signup</button></a>
	<% end %>
</div>



<!-- lists all posts in order of most recent -->

app/views/posts/new.html.erb
<div class="posts-new">
	<% if current_user %>
		<%= bootstrap_form_for Post.new do |f| %>
			<%= f.text_field :title %>
		<br>
			<%= f.text_area :content %>
		<br>
		<%= f.submit %>
		<% end %>
		<% else %>
		<h2>Please Sign In</h2>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="posts-show">
	<% if current_user %>
	<h1><%= @post.title %></h1>
	<br>
	<h4> User: <a href="/users/<%= @user.id %>"> <%= @user.username %> </a> </h4>
	<br>
	<p>
		<%= @post.content %>
		<%= link_to "Edit", edit_post_path(@post) %>
	</p>
	<br>
	<br>
	<h1>Comments: </h1>
		<% @comments.each do |comment| %>
					<h4>Posted by: <%= comment.user.username %></h4>
					<p><%= comment.content%></p>
					<br>
			<% end %>
	<%= link_to "Add Comment", new_comment_path(post_id: @post.id) %>
	<% end %>
</div>

<!-- full view of posts including comments -->

app/views/users/_user_form.html.erb
	<%= bootstrap_form_for @user do |f| %>
		<%= f.text_field :username %>
	<br>
		<%= f.text_field :email %>
	<br>
		<%= f.password_field :password %>
	<br>
	<%= f.submit %>
	<% end %>

app/views/users/edit.html.erb
<div class="users-edit">
	<% if current_user %>
		<%= render "user_form" %>
	<% end %>
</div>

<!-- edit user profile page -->

app/views/users/new.html.erb
<div class="users-new">
	<%= render "user_form" %>
</div>

<!-- user signup page -->

app/views/users/show.html.erb
<div class="users-show">
	<% if current_user %>
	<h1><%= @user.username %></h1>
		<p>
			<p>E-mail:
			<%= @user.email %>
			</p>
			<br>
			<%= link_to "Edit", edit_user_path(@user) %>
		</p>
	<% end %>
</div>

<!-- users profile page -->